/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEVrQnFkVHZud3NjMzNXZEZrdU1FZ0xLa0JSS1EvTDVmV0x4UlNEMEEwQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid09ub1U0M080WGZFUjNHRTdoTmFGSThmSkNwWTNNcXdlaDRmQTBhelQzND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFS2gyYW94ZDBxVWxjZ3NXUEM2ek5nclFHakhoaW9LRDlmQjN6ZHVqSDBrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6eVZxMVRyS3ZOWWxIdzkwVERMdjZUVk9XWnZuamJZRmFlWkg0OU9LdW5VPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9KcmRRS0dHUEsrckdBc1BXS1krQlNUb1lpS1JIcnVkbDc1V0lqWXRpWFU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkQ4aHdtRTF5WUNhS1IweFhBMVRtN1p5Nzk5QVdWaU40cTNDaTh0RGNVM009In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSU56UHJTb05VNGxVNEQ1Wk8xNHNTWkRjcWltYXowMDlPNjg3TmprNGpVdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNU1lUzVPanp3cFV3VWxhVHVvUDUxQ1Q4d2V6cDYycXRQc3YwWEZSL3RnTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImhCOFV0cVRKdVVhdHR6RjFybzZjTlU1UlR5cXZlcDM1aGFyVklSMGdaSGR6TjlPOG5wejl1VXZkaS81RDNMd21NT2x6U09VbEhyZmxEcm1oRmFRMmhRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTkxLCJhZHZTZWNyZXRLZXkiOiJzQWd5SjZtLys3c1lvN2RhS1BDUWtSSVYvRGY4NWE0RC9pZWdRRjlzR0c4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcxMzk1MjMyOUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBOTIwQzIyRTgwREM3N0YzMTBBNThGMkZDRUM4MDQzQiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIxNTExODkyfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3MTM5NTIzMjlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiN0I2NEZBNUZEQUQ5QzUxQTg0NDAxOTRFRjVDMTRDOTcifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyMTUxMTg5M31dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiTGtnMGZuY0hUaU9NUzVzNWE3bHZKQSIsInBob25lSWQiOiJkYTQwNDgwMi00YzJiLTRkNzItYWNlZi0zMWE1N2E2YzU4NTYiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaVgxaUxTUFlCbzBEVlJybFNNcmNHZ1p2M0JvPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9kWlVvNHZ3SFdNalJqemJCTVE5bm1ZY3Z5UT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJFMzdQOE43QSIsIm1lIjp7ImlkIjoiMjU0NzEzOTUyMzI5OjE2QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IlNoZWNraWUg8J+HuvCfh7gifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ1B6SC9oSVF1ZC93dEFZWUJTQUFLQUE9IiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IkxWK2ZHY1RRenRaWlhUWlRBOEc2MFE0anJKWElVbzhHaHVtNWdoRGovMEk9IiwiYWNjb3VudFNpZ25hdHVyZSI6InlPTVhkU2dDOUhjVDlwTU56MzRNNXBwVHRwV29ieFo2MGRVTlJrbkt0WTMwSFNoN1ZFcmlBbHliU3pVV1VvZDNTcElsaHhpNjRXR2IxNXE2czROK0F3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJlWHFuTmdWMzlSMUJCdVMwQzMvVVkvR0orOWhpMmc2eEtITEV3eEJ1bE1PamFIUngyTXZVZkZhanNSeWxvSTRSMFNzMktzbUIrczkxUEhYems3OGFpUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDcxMzk1MjMyOToxNkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJTMWZueG5FME03V1dWMDJVd1BCdXRFT0k2eVZ5RktQQm9icHVZSVE0LzlDIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzIxNTExODc5LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUZmNSJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Sheckie';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254713952329';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'Sheckiebot';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'true';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'typing';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'true';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session
};
